//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICT.Console.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICT.Console.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =========================.
        /// </summary>
        internal static string ICTApplicationUnderWelcomeMessage {
            get {
                return ResourceManager.GetString("ICTApplicationUnderWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the ICT System.
        /// </summary>
        internal static string ICTApplicationWelcomeMessage {
            get {
                return ResourceManager.GetString("ICTApplicationWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes: {0}.
        /// </summary>
        internal static string ICTAvailableRoutesMessage {
            get {
                return ResourceManager.GetString("ICTAvailableRoutesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current cities: {0}.
        /// </summary>
        internal static string ICTCurrentCitiesMessage {
            get {
                return ResourceManager.GetString("ICTCurrentCitiesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current links: {0}.
        /// </summary>
        internal static string ICTCurrentLinksMessage {
            get {
                return ResourceManager.GetString("ICTCurrentLinksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB5 BC4 CD8 DC8 DE6 AD5 CE2 EB3 AE7.
        /// </summary>
        internal static string ICTDefaultConnectorData {
            get {
                return ResourceManager.GetString("ICTDefaultConnectorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NONE.
        /// </summary>
        internal static string ICTEmptyCollectionMessage {
            get {
                return ResourceManager.GetString("ICTEmptyCollectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Enter new link definition [XX#]:.
        /// </summary>
        internal static string ICTEnterLinkDefinitionMessage {
            get {
                return ResourceManager.GetString("ICTEnterLinkDefinitionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Enter maximum distance [#]:.
        /// </summary>
        internal static string ICTEnterMaxDistanceMessage {
            get {
                return ResourceManager.GetString("ICTEnterMaxDistanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Enter maximum number of stops [#]:.
        /// </summary>
        internal static string ICTEnterMaxNumStopsMessage {
            get {
                return ResourceManager.GetString("ICTEnterMaxNumStopsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Enter option:.
        /// </summary>
        internal static string ICTEnterOptionMessage {
            get {
                return ResourceManager.GetString("ICTEnterOptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Enter route definition [X X ...]:.
        /// </summary>
        internal static string ICTEnterRouteDefinitionMessage {
            get {
                return ResourceManager.GetString("ICTEnterRouteDefinitionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Enter start and final citties [X X]:.
        /// </summary>
        internal static string ICTEnterTargetCitiesMessage {
            get {
                return ResourceManager.GetString("ICTEnterTargetCitiesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid city definition.
        /// </summary>
        internal static string ICTInvalidCityDefinitionMessage {
            get {
                return ResourceManager.GetString("ICTInvalidCityDefinitionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid link definition.
        /// </summary>
        internal static string ICTInvalidLinkDefinitionMessage {
            get {
                return ResourceManager.GetString("ICTInvalidLinkDefinitionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid route definition.
        /// </summary>
        internal static string ICTInvalidRouteDefinitionMessage {
            get {
                return ResourceManager.GetString("ICTInvalidRouteDefinitionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid route limitation.
        /// </summary>
        internal static string ICTInvalidRouteLimitationDefinitionMessage {
            get {
                return ResourceManager.GetString("ICTInvalidRouteLimitationDefinitionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link {0} already exists.
        /// </summary>
        internal static string ICTLinkAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("ICTLinkAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum distance: {0}.
        /// </summary>
        internal static string ICTMinimumDistanceMessage {
            get {
                return ResourceManager.GetString("ICTMinimumDistanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} route presents the minimum distance.
        /// </summary>
        internal static string ICTMinimumDistanceRouteMessage {
            get {
                return ResourceManager.GetString("ICTMinimumDistanceRouteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key....
        /// </summary>
        internal static string ICTPressAnyKeyMessage {
            get {
                return ResourceManager.GetString("ICTPressAnyKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance: {0}.
        /// </summary>
        internal static string ICTRouteDistanceMessage {
            get {
                return ResourceManager.GetString("ICTRouteDistanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route {0} is available.
        /// </summary>
        internal static string ICTRouteIsAvailableMessage {
            get {
                return ResourceManager.GetString("ICTRouteIsAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO SUCH ROUTE.
        /// </summary>
        internal static string ICTRouteIsNotAvailableMessage {
            get {
                return ResourceManager.GetString("ICTRouteIsNotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO SUCH ROUTES.
        /// </summary>
        internal static string ICTRoutesAreNotAvailableMessage {
            get {
                return ResourceManager.GetString("ICTRoutesAreNotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Select one of the following options:.
        /// </summary>
        internal static string ICTSelectOptionMessage {
            get {
                return ResourceManager.GetString("ICTSelectOptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-referencing links ({0}) are not allowed.
        /// </summary>
        internal static string ICTSelfReferencingLinksMessage {
            get {
                return ResourceManager.GetString("ICTSelfReferencingLinksMessage", resourceCulture);
            }
        }
    }
}
